-- ============================================================
-- hr.db 数据库变更脚本 v2
-- 新增loginname字段 + 默认密码xdt888 + 清空假种子 + 导入真实员工
-- 执行前请备份 hr.db
-- ============================================================

-- Step 1: 新增登录账号字段
ALTER TABLE employees ADD COLUMN loginname TEXT DEFAULT '';

-- Step 2: 设置默认密码（如已有password字段则UPDATE，否则新增）
-- 若employees表已有password字段：
UPDATE employees SET password = 'xdt888' WHERE password IS NULL OR password = '';
-- 若无password字段，先执行：
-- ALTER TABLE employees ADD COLUMN password TEXT DEFAULT 'xdt888';

-- Step 3: 清空假种子数据
DELETE FROM employees WHERE id < 100;

-- Step 4: 导入真实员工数据
-- 字段映射：OA → hr.db
--   staff_id → id, name → name, gender 男→M/女→F
--   company_id → company_id, department_id → department_id
--   loginname → loginname(新增), password默认xdt888
--   mobile → phone, email → email, birthday → birth_date
--   education → education, hire_date → hire_date
--   state在职→active

-- 共 108 条在职员工

INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (252, '肖素芬', 'M', 1, 6, 'sinocro-xiaosufen', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (773, '董剑峰', 'M', 1, 6, 'sinocro-dongjianfeng', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (970, '袁慧莹', 'M', 1, 6, 'sinocro-yuanhuiying', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (996, '杜天北', 'M', 1, 6, 'sinocro-dutianbei', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1076, '赵茜楠', 'M', 1, 6, 'sinocro-zhaoxinan', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1082, '豆瑞涛', 'M', 1, 6, 'sinocro-douruitao', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (698, '王萌萌', 'M', 1, 7, 'sinocro-wangmengmeng', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (713, '冯杨', 'M', 1, 7, 'sinocro-fengyang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (721, '李明', 'M', 1, 7, 'sinocro-liming', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (871, '顾益如', 'M', 1, 7, 'sinocro-guyiru', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1058, '郭潼', 'M', 1, 7, 'sinocro-guotong', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (863, '王惠惠', 'M', 1, 10, 'sinocro-wanghuihui', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (869, '王宏赟', 'M', 1, 10, 'sinocro-wanghongyun', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1010, '王凤萍', 'M', 1, 10, 'sinocro-wangfengping', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (994, '张维佳', 'M', 1, 13, 'sinocro-zhangweijia', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1003, '闫晓涵', 'M', 1, 13, 'sinocro-yanxiaohan', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1029, '杨钒', 'M', 1, 13, 'sinocro-yangfan', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1037, '李明喆', 'M', 1, 13, 'sinocro-limingzhe', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1048, '吴鑫鑫', 'M', 1, 13, 'sinocro-wuxinxin', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1081, '温兆瑞', 'M', 1, 13, 'sinocro-wenzhaorui', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1083, '常旺', 'M', 1, 13, 'sinocro-changwang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1085, '塞比热', 'M', 1, 13, 'sinocro-saibire', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (739, '医学运营部', 'M', 1, 14, 'sop04', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1013, '辅助账号LW', 'M', 1, 14, 'sinocro-LW', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1084, '杨平', 'M', 1, 14, 'sinocro-yangping', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (341, '刘暾', 'M', 1, 15, 'sinocro-liutun', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (523, '霍秀琴', 'M', 1, 15, 'sinocro-huoxiuqin', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (611, '钱晟', 'F', 1, 15, 'sinocro-qiansheng', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (695, '胡浩臻', 'M', 1, 15, 'sinocro-huhaozhen', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (737, '数据部', 'M', 1, 15, 'sop02', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (799, '庞浩鑫', 'M', 1, 15, 'sinocro-panghaoxin', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (929, '徐贤祥', 'M', 1, 15, 'sinocro-xuxianxiang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (70, '陈得支', 'M', 1, 17, 'sinocro-chendezhi', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (488, '质保培训部', 'F', 1, 17, 'sinocro-qau', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (720, 'OA小助手', 'M', 1, 17, 'OA小助手', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (744, '质保培训部', 'M', 1, 17, 'sop06', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1027, '胡雅', 'F', 1, 17, 'sinocro-huya', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1074, '梁惟', 'M', 1, 17, 'sinocro-liangwei', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (917, '稽查1', 'M', 1, 104, 'jc01', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (918, '稽查2', 'M', 1, 104, 'jc02', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (919, '稽查3', 'M', 1, 104, 'jc03', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (920, '稽查4', 'M', 1, 104, 'jc04', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (921, '稽查5', 'M', 1, 104, 'jc05', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (953, '外部核查（运营）', 'M', 1, 104, 'HC01', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (959, '外部核查（运营02）', 'M', 1, 104, 'HC02', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1020, '运营03', 'M', 1, 104, 'hc03', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1055, '运营05', 'M', 1, 104, 'HC05', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1056, '运营04', 'M', 1, 104, 'HC04', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1071, '核查06', 'M', 1, 104, 'HC06', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1072, '核查07', 'M', 1, 104, 'HC07', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1073, '核查08', 'M', 1, 104, 'HC08', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (808, '叶枫', 'M', 1, 252, 'sinocro-yefeng', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (851, '刘宇丹', 'M', 1, 252, 'sinocro-liuyudan', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1024, '谢超', 'M', 1, 260, 'sinocro-xiechao', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1030, '田芳', 'M', 1, 305, 'sinocro-tianfang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1034, '李强', 'M', 1, 305, 'sinocro-liqiang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1057, '刘军', 'M', 1, 305, 'sinocro-liujun', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1065, '李雨静', 'M', 1, 305, 'sinocro-liyujing', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (738, '药物警戒部', 'M', 1, 322, 'sop03', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (65, '黄哲', 'M', 1, 353, 'sinocro-huangzhe', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (982, '景宁', 'M', 1, 421, 'sinocro-jingning', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1005, '赖竞成', 'M', 1, 421, 'sinocro-laijingcheng', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1009, '陈建', 'M', 1, 421, 'sinocro-chenjian2024', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1042, '高媛', 'M', 1, 421, 'sinocro-gaoyuan2025', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (543, '王博', 'F', 1, 423, 'sinocro-wangbo', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1033, '唐晓东', 'M', 1, 423, 'sinocro-tangxiaodong', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1059, '余荣波', 'M', 1, 423, 'sinocro-yurongbo', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1075, '兰梓溶', 'M', 1, 423, 'sinocro-lanzirong', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1077, '王新宇', 'M', 1, 423, 'sinocro-wangxinyu', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1049, '高腾飞', 'M', 1, 550, 'sinocro-gaotengfei', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (49, '梁潇', 'M', 1, 573, 'sinocro-liangxiao', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (48, '黄明光', 'M', 1, 590, 'hmg', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (925, '测试账号', 'M', 4, 266, 'gl', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (753, '测试mx', 'M', 5, 342, 'mx-ceshi', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (736, '质控资料员', 'M', 6, 0, 'smo-wuyanbin', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (619, '左静', 'M', 6, 359, 'sinocro-zuojing', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (740, '首辅医学', 'M', 6, 424, 'sop07', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (513, '刘瑄', 'M', 6, 426, 'smo-liuxuan', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (997, '鲁维青', 'M', 6, 427, 'smo-luweiqing', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1051, '杨思', 'M', 6, 427, 'smo-yangsi', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1062, '高璋', 'M', 6, 427, 'smo-gaozhang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1064, '王卓婧', 'M', 6, 427, 'smo-wangzhuojing', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (750, '刘凌', 'M', 6, 428, 'smo-liuling', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (960, '向梦娇', 'M', 6, 428, 'smo-xiangmengjiao', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (525, '符施恩', 'M', 6, 430, 'smo-fushien', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (831, '宫景霞', 'M', 6, 430, 'sinocro-gongjingxia', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (875, '张昕', 'M', 9, 374, 'cyjc-zhangxin', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (876, '李冬艳', 'M', 9, 375, 'cyjc-lidongyan', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (880, '王继勇', 'M', 9, 375, 'cyjc-wangjiyong', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (881, '田立明', 'M', 9, 375, 'cyjc-tianliming', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (882, '赵君平', 'M', 9, 375, 'cyjc-zhaojunping', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1063, '王小杰', 'M', 9, 375, 'cyjc-wangxiaojie', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (883, '孙晓红', 'M', 9, 376, 'cyjc-sunxiaohong', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (884, '孙伟娜', 'M', 9, 377, 'cyjc-sunweina', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (885, '杨雪梅', 'M', 9, 378, 'cyjc-yangxuemei', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (887, '谷波', 'M', 9, 378, 'cyjc-gubo', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (888, '崔龙', 'M', 9, 378, 'cyjc-cuilong', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (889, '于慧洋', 'M', 9, 378, 'cyjc-yuhuiyang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (890, '王志伟', 'M', 9, 378, 'cyjc-wangzhiwei', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (893, '姜中广', 'M', 9, 378, 'cyjc-jiangzhongguang', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (894, '徐志丹', 'M', 9, 378, 'cyjc-xuzhidan', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (895, '郑亚斌', 'M', 9, 378, 'cyjc-zhengyabin', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (900, '刘忠原', 'F', 9, 378, 'cyjc-liuzhongyuan1', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (958, '李辉', 'M', 9, 378, 'cyjc-lihui', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1066, '于鸽', 'M', 9, 378, 'cyjc-yuge', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1078, '曾庆超', 'M', 11, 592, 'xjsw-zqc', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1079, '黄保嘉', 'M', 11, 593, 'xjsw-hbj', 'xdt888', '', '', '', '', '', 'active');
INSERT OR IGNORE INTO employees (id, name, gender, company_id, department_id, loginname, password, phone, email, birth_date, education, hire_date, employment_status) VALUES (1080, '赵君平（xjr）', 'M', 11, 594, 'xjsw-zhaojunping', 'xdt888', '', '', '', '', '', 'active');

-- 完成: 108 条记录
